
// This file has been generated by the GUI designer. Do not modify.
namespace DatabaseCreator
{
	public partial class Edit
	{
		private global::Gtk.VBox vbox1;
		
		private global::Gtk.HBox hbox3;
		
		private global::Gtk.Label label1;
		
		private global::Gtk.Entry scriptNameEntry;
		
		private global::Gtk.HBox hbox6;
		
		private global::Gtk.Label label2;
		
		private global::Gtk.Entry scriptURL;
		
		private global::Gtk.HBox hbox7;
		
		private global::Gtk.Label label3;
		
		private global::Gtk.Entry resourceURL;
		
		private global::Gtk.HBox hbox4;
		
		private global::Gtk.Label label4;
		
		private global::Gtk.Entry screenshotURL;
		
		private global::Gtk.HBox hbox5;
		
		private global::Gtk.Label label5;
		
		private global::Gtk.ScrolledWindow GtkScrolledWindow;
		
		private global::Gtk.TextView usageExample;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget DatabaseCreator.Edit
			global::Stetic.BinContainer.Attach (this);
			this.Name = "DatabaseCreator.Edit";
			// Container child DatabaseCreator.Edit.Gtk.Container+ContainerChild
			this.vbox1 = new global::Gtk.VBox ();
			this.vbox1.Name = "vbox1";
			this.vbox1.Spacing = 6;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox3 = new global::Gtk.HBox ();
			this.hbox3.Name = "hbox3";
			this.hbox3.Spacing = 6;
			// Container child hbox3.Gtk.Box+BoxChild
			this.label1 = new global::Gtk.Label ();
			this.label1.Name = "label1";
			this.label1.LabelProp = global::Mono.Unix.Catalog.GetString ("Script Name:");
			this.hbox3.Add (this.label1);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.label1]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			// Container child hbox3.Gtk.Box+BoxChild
			this.scriptNameEntry = new global::Gtk.Entry ();
			this.scriptNameEntry.CanFocus = true;
			this.scriptNameEntry.Name = "scriptNameEntry";
			this.scriptNameEntry.IsEditable = true;
			this.scriptNameEntry.InvisibleChar = '●';
			this.hbox3.Add (this.scriptNameEntry);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.scriptNameEntry]));
			w2.Position = 1;
			this.vbox1.Add (this.hbox3);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox3]));
			w3.Position = 0;
			w3.Expand = false;
			w3.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox6 = new global::Gtk.HBox ();
			this.hbox6.Name = "hbox6";
			this.hbox6.Spacing = 6;
			// Container child hbox6.Gtk.Box+BoxChild
			this.label2 = new global::Gtk.Label ();
			this.label2.Name = "label2";
			this.label2.LabelProp = global::Mono.Unix.Catalog.GetString ("Script URL (.lua):");
			this.hbox6.Add (this.label2);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox6 [this.label2]));
			w4.Position = 0;
			w4.Expand = false;
			w4.Fill = false;
			// Container child hbox6.Gtk.Box+BoxChild
			this.scriptURL = new global::Gtk.Entry ();
			this.scriptURL.CanFocus = true;
			this.scriptURL.Name = "scriptURL";
			this.scriptURL.IsEditable = true;
			this.scriptURL.InvisibleChar = '●';
			this.hbox6.Add (this.scriptURL);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox6 [this.scriptURL]));
			w5.Position = 1;
			this.vbox1.Add (this.hbox6);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox6]));
			w6.Position = 1;
			w6.Expand = false;
			w6.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox7 = new global::Gtk.HBox ();
			this.hbox7.Name = "hbox7";
			this.hbox7.Spacing = 6;
			// Container child hbox7.Gtk.Box+BoxChild
			this.label3 = new global::Gtk.Label ();
			global::Gtk.Tooltips w7 = new Gtk.Tooltips ();
			w7.SetTip (this.label3, "If your script has no resources, leave this blank", "If your script has no resources, leave this blank");
			this.label3.Name = "label3";
			this.label3.LabelProp = global::Mono.Unix.Catalog.GetString ("Resource URL (.zip):");
			this.hbox7.Add (this.label3);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hbox7 [this.label3]));
			w8.Position = 0;
			w8.Expand = false;
			w8.Fill = false;
			// Container child hbox7.Gtk.Box+BoxChild
			this.resourceURL = new global::Gtk.Entry ();
			this.resourceURL.CanFocus = true;
			this.resourceURL.Name = "resourceURL";
			this.resourceURL.IsEditable = true;
			this.resourceURL.InvisibleChar = '●';
			this.hbox7.Add (this.resourceURL);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.hbox7 [this.resourceURL]));
			w9.Position = 1;
			this.vbox1.Add (this.hbox7);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox7]));
			w10.Position = 2;
			w10.Expand = false;
			w10.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox4 = new global::Gtk.HBox ();
			this.hbox4.Name = "hbox4";
			this.hbox4.Spacing = 6;
			// Container child hbox4.Gtk.Box+BoxChild
			this.label4 = new global::Gtk.Label ();
			this.label4.Name = "label4";
			this.label4.LabelProp = global::Mono.Unix.Catalog.GetString ("Screenshot URL: ");
			this.hbox4.Add (this.label4);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.label4]));
			w11.Position = 0;
			w11.Expand = false;
			w11.Fill = false;
			// Container child hbox4.Gtk.Box+BoxChild
			this.screenshotURL = new global::Gtk.Entry ();
			this.screenshotURL.CanFocus = true;
			this.screenshotURL.Name = "screenshotURL";
			this.screenshotURL.IsEditable = true;
			this.screenshotURL.InvisibleChar = '●';
			this.hbox4.Add (this.screenshotURL);
			global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.screenshotURL]));
			w12.Position = 1;
			this.vbox1.Add (this.hbox4);
			global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox4]));
			w13.Position = 3;
			w13.Expand = false;
			w13.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox5 = new global::Gtk.HBox ();
			this.hbox5.Name = "hbox5";
			this.hbox5.Spacing = 6;
			// Container child hbox5.Gtk.Box+BoxChild
			this.label5 = new global::Gtk.Label ();
			this.label5.Name = "label5";
			this.label5.LabelProp = global::Mono.Unix.Catalog.GetString ("Usage Example:");
			this.hbox5.Add (this.label5);
			global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.hbox5 [this.label5]));
			w14.Position = 0;
			w14.Expand = false;
			w14.Fill = false;
			// Container child hbox5.Gtk.Box+BoxChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow.HeightRequest = 254;
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.usageExample = new global::Gtk.TextView ();
			this.usageExample.CanFocus = true;
			this.usageExample.Name = "usageExample";
			this.GtkScrolledWindow.Add (this.usageExample);
			this.hbox5.Add (this.GtkScrolledWindow);
			global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.hbox5 [this.GtkScrolledWindow]));
			w16.Position = 1;
			this.vbox1.Add (this.hbox5);
			global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox5]));
			w17.Position = 4;
			w17.Expand = false;
			w17.Fill = false;
			this.Add (this.vbox1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
		}
	}
}
