
// This file has been generated by the GUI designer. Do not modify.
namespace Gtktester
{
	public partial class AskForLunaLuaWindow
	{
		private global::Gtk.VBox vbox2;
		
		private global::Gtktester.AskForLunaLuaWidget askforlunaluawidget1;
		
		private global::Gtk.HBox hbox1;
		
		private global::Gtk.Button nextButton;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget Gtktester.AskForLunaLuaWindow
			this.Name = "Gtktester.AskForLunaLuaWindow";
			this.Title = "";
			this.Icon = global::Gdk.Pixbuf.LoadFromResource ("Gtktester.Icons.PNG.32.png");
			this.WindowPosition = ((global::Gtk.WindowPosition)(1));
			this.BorderWidth = ((uint)(6));
			this.Resizable = false;
			// Container child Gtktester.AskForLunaLuaWindow.Gtk.Container+ContainerChild
			this.vbox2 = new global::Gtk.VBox ();
			this.vbox2.Name = "vbox2";
			this.vbox2.Spacing = 6;
			// Container child vbox2.Gtk.Box+BoxChild
			this.askforlunaluawidget1 = new global::Gtktester.AskForLunaLuaWidget ();
			this.askforlunaluawidget1.Events = ((global::Gdk.EventMask)(256));
			this.askforlunaluawidget1.Name = "askforlunaluawidget1";
			this.vbox2.Add (this.askforlunaluawidget1);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.askforlunaluawidget1]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.hbox1 = new global::Gtk.HBox ();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.nextButton = new global::Gtk.Button ();
			this.nextButton.WidthRequest = 120;
			this.nextButton.CanFocus = true;
			this.nextButton.Name = "nextButton";
			this.nextButton.UseUnderline = true;
			this.nextButton.Label = "Next";
			this.hbox1.Add (this.nextButton);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.nextButton]));
			w2.Position = 2;
			w2.Expand = false;
			w2.Fill = false;
			this.vbox2.Add (this.hbox1);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.hbox1]));
			w3.Position = 1;
			w3.Expand = false;
			w3.Fill = false;
			this.Add (this.vbox2);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 601;
			this.DefaultHeight = 272;
			this.Show ();
			this.nextButton.Clicked += new global::System.EventHandler (this.OnButtonNextClick);
		}
	}
}
