
// This file has been generated by the GUI designer. Do not modify.
namespace Gtktester
{
	public partial class LunaLuaInformation
	{
		private global::Gtk.VBox vbox2;
		
		private global::Gtk.Label curLunaLuaVersion;
		
		private global::Gtk.Button button17;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget Gtktester.LunaLuaInformation
			global::Stetic.BinContainer.Attach (this);
			this.Name = "Gtktester.LunaLuaInformation";
			// Container child Gtktester.LunaLuaInformation.Gtk.Container+ContainerChild
			this.vbox2 = new global::Gtk.VBox ();
			this.vbox2.Name = "vbox2";
			this.vbox2.Spacing = 6;
			// Container child vbox2.Gtk.Box+BoxChild
			this.curLunaLuaVersion = new global::Gtk.Label ();
			this.curLunaLuaVersion.Name = "curLunaLuaVersion";
			this.curLunaLuaVersion.LabelProp = "Your Current LunaLua Version is: {0}";
			this.vbox2.Add (this.curLunaLuaVersion);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.curLunaLuaVersion]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.button17 = new global::Gtk.Button ();
			this.button17.CanFocus = true;
			this.button17.Name = "button17";
			this.button17.UseUnderline = true;
			this.button17.Label = "Install/Update";
			this.vbox2.Add (this.button17);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.button17]));
			w2.Position = 2;
			w2.Expand = false;
			w2.Fill = false;
			this.Add (this.vbox2);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
		}
	}
}
