
// This file has been generated by the GUI designer. Do not modify.
namespace Gtktester
{
	public partial class FirstRunWindow
	{
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget Gtktester.FirstRunWindow
			this.Name = "Gtktester.FirstRunWindow";
			this.Title = global::Mono.Unix.Catalog.GetString ("FirstRunWindow");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 400;
			this.DefaultHeight = 300;
			this.Show ();
		}
	}
}
