
// This file has been generated by the GUI designer. Do not modify.
namespace Gtktester
{
	public partial class CheckForUpdatesProgress
	{
		private global::Gtk.Label label1;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget Gtktester.CheckForUpdatesProgress
			this.Name = "Gtktester.CheckForUpdatesProgress";
			this.Title = global::Mono.Unix.Catalog.GetString ("CheckForUpdatesProgress");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			this.Modal = true;
			this.Resizable = false;
			this.DefaultWidth = 250;
			this.DefaultHeight = 90;
			// Container child Gtktester.CheckForUpdatesProgress.Gtk.Container+ContainerChild
			this.label1 = new global::Gtk.Label ();
			this.label1.Name = "label1";
			this.label1.LabelProp = global::Mono.Unix.Catalog.GetString ("Checking for updates..");
			this.Add (this.label1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Show ();
		}
	}
}
