
// This file has been generated by the GUI designer. Do not modify.
namespace Gtktester
{
	public partial class Downloader
	{
		private global::Gtk.Fixed fixed1;
		
		private global::Gtk.ProgressBar progressbar1;
		
		private global::Gtk.Label speedLabel;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget Gtktester.Downloader
			this.Name = "Gtktester.Downloader";
			this.Title = "Downloader";
			this.Icon = global::Gdk.Pixbuf.LoadFromResource ("Gtktester.Icons.PNG.32.png");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			this.Modal = true;
			this.Resizable = false;
			this.AllowGrow = false;
			// Container child Gtktester.Downloader.Gtk.Container+ContainerChild
			this.fixed1 = new global::Gtk.Fixed ();
			this.fixed1.Name = "fixed1";
			this.fixed1.HasWindow = false;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.progressbar1 = new global::Gtk.ProgressBar ();
			this.progressbar1.WidthRequest = 470;
			this.progressbar1.Name = "progressbar1";
			this.progressbar1.Text = "TODO: 0kb/100kb";
			this.fixed1.Add (this.progressbar1);
			global::Gtk.Fixed.FixedChild w1 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.progressbar1]));
			w1.X = 20;
			w1.Y = 61;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.speedLabel = new global::Gtk.Label ();
			this.speedLabel.WidthRequest = 467;
			this.speedLabel.Name = "speedLabel";
			this.speedLabel.LabelProp = "0 Mb/s";
			this.fixed1.Add (this.speedLabel);
			global::Gtk.Fixed.FixedChild w2 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.speedLabel]));
			w2.X = 21;
			w2.Y = 88;
			this.Add (this.fixed1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 512;
			this.DefaultHeight = 150;
			this.Show ();
		}
	}
}
