
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.UIManager UIManager;
	
	private global::Gtk.Action LunaLuaModuleManagerAction;
	
	private global::Gtk.Action dialogInfoAction;
	
	private global::Gtk.Action preferencesAction;
	
	private global::Gtk.Action quitAction;
	
	private global::Gtk.Action convertAction;
	
	private global::Gtk.VBox vbox1;
	
	private global::Gtk.MenuBar menubar1;
	
	private global::Gtk.Notebook notebook1;
	
	private global::Gtk.HPaned hpaned2;
	
	private global::Gtk.ScrolledWindow GtkScrolledWindow;
	
	private global::Gtk.TreeView treeview1;
	
	private global::Gtktester.InformationView informationview1;
	
	private global::Gtk.Label label1;
	
	private global::Gtk.HPaned hpaned1;
	
	private global::Gtk.ScrolledWindow GtkScrolledWindow2;
	
	private global::Gtk.TreeView lunaLuaVersionsTree;
	
	private global::Gtktester.LunaLuaInformation lunaluainformation1;
	
	private global::Gtk.Label label2;

	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.UIManager = new global::Gtk.UIManager ();
		global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup ("Default");
		this.LunaLuaModuleManagerAction = new global::Gtk.Action ("LunaLuaModuleManagerAction", "_LunaLua Module Manager", null, null);
		this.LunaLuaModuleManagerAction.ShortLabel = "LunaLua Module Manager";
		w1.Add (this.LunaLuaModuleManagerAction, null);
		this.dialogInfoAction = new global::Gtk.Action ("dialogInfoAction", "About", null, "gtk-dialog-info");
		this.dialogInfoAction.ShortLabel = "About";
		w1.Add (this.dialogInfoAction, null);
		this.preferencesAction = new global::Gtk.Action ("preferencesAction", "Settings", null, "gtk-preferences");
		this.preferencesAction.ShortLabel = "Settings";
		w1.Add (this.preferencesAction, null);
		this.quitAction = new global::Gtk.Action ("quitAction", "_Close", null, "gtk-quit");
		this.quitAction.IsImportant = true;
		this.quitAction.ShortLabel = "_Close";
		w1.Add (this.quitAction, null);
		this.convertAction = new global::Gtk.Action ("convertAction", "_Bug Reporter", null, "gtk-convert");
		this.convertAction.ShortLabel = "_Bug Reporter";
		w1.Add (this.convertAction, null);
		this.UIManager.InsertActionGroup (w1, 0);
		this.AddAccelGroup (this.UIManager.AccelGroup);
		this.Name = "MainWindow";
		this.Title = "Lua Module Manager - v0.0.0.0";
		this.Icon = global::Gdk.Pixbuf.LoadFromResource ("Gtktester.Icons.PNG.32.png");
		this.WindowPosition = ((global::Gtk.WindowPosition)(1));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox1 = new global::Gtk.VBox ();
		this.vbox1.Name = "vbox1";
		this.vbox1.Spacing = 6;
		// Container child vbox1.Gtk.Box+BoxChild
		this.UIManager.AddUiFromString (@"<ui><menubar name='menubar1'><menu name='LunaLuaModuleManagerAction' action='LunaLuaModuleManagerAction'><menuitem name='dialogInfoAction' action='dialogInfoAction'/><menuitem name='preferencesAction' action='preferencesAction'/><menuitem name='quitAction' action='quitAction'/><menuitem name='convertAction' action='convertAction'/></menu></menubar></ui>");
		this.menubar1 = ((global::Gtk.MenuBar)(this.UIManager.GetWidget ("/menubar1")));
		this.menubar1.Name = "menubar1";
		this.vbox1.Add (this.menubar1);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.menubar1]));
		w2.Position = 0;
		w2.Expand = false;
		w2.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.notebook1 = new global::Gtk.Notebook ();
		this.notebook1.CanFocus = true;
		this.notebook1.Name = "notebook1";
		this.notebook1.CurrentPage = 1;
		this.notebook1.TabPos = ((global::Gtk.PositionType)(3));
		// Container child notebook1.Gtk.Notebook+NotebookChild
		this.hpaned2 = new global::Gtk.HPaned ();
		this.hpaned2.CanFocus = true;
		this.hpaned2.Name = "hpaned2";
		this.hpaned2.Position = 1;
		// Container child hpaned2.Gtk.Paned+PanedChild
		this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
		this.GtkScrolledWindow.WidthRequest = 250;
		this.GtkScrolledWindow.Name = "GtkScrolledWindow";
		this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
		this.treeview1 = new global::Gtk.TreeView ();
		this.treeview1.WidthRequest = 250;
		this.treeview1.CanFocus = true;
		this.treeview1.Name = "treeview1";
		this.GtkScrolledWindow.Add (this.treeview1);
		this.hpaned2.Add (this.GtkScrolledWindow);
		global::Gtk.Paned.PanedChild w4 = ((global::Gtk.Paned.PanedChild)(this.hpaned2 [this.GtkScrolledWindow]));
		w4.Resize = false;
		// Container child hpaned2.Gtk.Paned+PanedChild
		this.informationview1 = new global::Gtktester.InformationView ();
		this.informationview1.Events = ((global::Gdk.EventMask)(256));
		this.informationview1.Name = "informationview1";
		this.hpaned2.Add (this.informationview1);
		this.notebook1.Add (this.hpaned2);
		// Notebook tab
		this.label1 = new global::Gtk.Label ();
		this.label1.Name = "label1";
		this.label1.LabelProp = "LunaLua Scripts";
		this.notebook1.SetTabLabel (this.hpaned2, this.label1);
		this.label1.ShowAll ();
		// Container child notebook1.Gtk.Notebook+NotebookChild
		this.hpaned1 = new global::Gtk.HPaned ();
		this.hpaned1.CanFocus = true;
		this.hpaned1.Name = "hpaned1";
		this.hpaned1.Position = 1;
		// Container child hpaned1.Gtk.Paned+PanedChild
		this.GtkScrolledWindow2 = new global::Gtk.ScrolledWindow ();
		this.GtkScrolledWindow2.Name = "GtkScrolledWindow2";
		this.GtkScrolledWindow2.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow2.Gtk.Container+ContainerChild
		this.lunaLuaVersionsTree = new global::Gtk.TreeView ();
		this.lunaLuaVersionsTree.CanFocus = true;
		this.lunaLuaVersionsTree.Name = "lunaLuaVersionsTree";
		this.GtkScrolledWindow2.Add (this.lunaLuaVersionsTree);
		this.hpaned1.Add (this.GtkScrolledWindow2);
		global::Gtk.Paned.PanedChild w8 = ((global::Gtk.Paned.PanedChild)(this.hpaned1 [this.GtkScrolledWindow2]));
		w8.Resize = false;
		// Container child hpaned1.Gtk.Paned+PanedChild
		this.lunaluainformation1 = new global::Gtktester.LunaLuaInformation ();
		this.lunaluainformation1.Events = ((global::Gdk.EventMask)(256));
		this.lunaluainformation1.Name = "lunaluainformation1";
		this.lunaluainformation1.wohlId = 0;
		this.hpaned1.Add (this.lunaluainformation1);
		this.notebook1.Add (this.hpaned1);
		global::Gtk.Notebook.NotebookChild w10 = ((global::Gtk.Notebook.NotebookChild)(this.notebook1 [this.hpaned1]));
		w10.Position = 1;
		// Notebook tab
		this.label2 = new global::Gtk.Label ();
		this.label2.Name = "label2";
		this.label2.LabelProp = "LunaLua";
		this.notebook1.SetTabLabel (this.hpaned1, this.label2);
		this.label2.ShowAll ();
		this.vbox1.Add (this.notebook1);
		global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.notebook1]));
		w11.Position = 1;
		this.Add (this.vbox1);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 800;
		this.DefaultHeight = 427;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this.dialogInfoAction.Activated += new global::System.EventHandler (this.OnAbout);
		this.preferencesAction.Activated += new global::System.EventHandler (this.OnPreferencesActionActivated);
		this.quitAction.Activated += new global::System.EventHandler (this.OnClosed);
		this.convertAction.Activated += new global::System.EventHandler (this.OnConvertActionActivated);
		this.treeview1.CursorChanged += new global::System.EventHandler (this.treeview_SelectionChanged);
		this.lunaLuaVersionsTree.CursorChanged += new global::System.EventHandler (this.OnLunaLuaVersionsTreeCursorChanged);
	}
}
